config:
  Name: buryPoint.rpc
  ListenOn: 192.168.124.10:9999
  BuryPointServerUrl: https://data.bbrjogo.com/
  BuryPointAppId: debug-appid

  Mode: dev
  GameConfig:
  Currency: BRL

  Kwai:
    AccessToken: cXXIHSSl+dpjNi7xXRJ94JOu+mG0D6OBqCQyeOfyaMo=

  Mysql:
    DataSource: root:123456@tcp(192.168.124.100:3306)/newfoguetebet?charset=utf8mb4&parseTime=true

  Etcd:
    Hosts:
      - 192.168.124.10:2379
    Key: buryPoint.rpc

  Cache:
    - Host: 192.168.124.10:6379

  Redis:
    Host: 192.168.124.10:6379
    Type: node

  Aws:
    AppId: xxxxxxx
    Secret: xxxxxxxx
    Region: sa-east-1
    OpenSearch:
      Remote: false
      Domain: http://192.168.124.10:9200