apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  labels:
    {{- include "es.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client