apiVersion: v1
kind: Service
metadata:
  name: es-node
  labels:
    {{- include "es.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 19200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "es.selectorLabels" . | nindent 4 }}
