config:
  Name: usercenter
  Host: 0.0.0.0
  Port: 80
  MaxBytes: 10485760
  Mode: dev

  JwtAuth:
    AccessSecret: ae0536f9-6450-4606-8e13-5a19ed505da0
    AccessExpire: 2592000

  Redis:
    Host: redis-master:6379
    Pass: game123456
    Type: node

  Aws:
    AppId: xxxxxxxx
    Secret: xxxxxxxxxx
    Region: sa-east-1
    OpenSearch:
      Remote: false
      Domain: http://es-node:9200


  UserRpc:
    #Target: k8s://dev1-game/user-rpc:80
    Endpoints:
      - user-rpc:80
    NonBlock: true

  BuryPointRpc:
    #Target: k8s://dev1-game/burypoint-rpc:80
    Endpoints:
      - burypoint-rpc:80
    NonBlock: true

  GameRpc:
    #Target: k8s://dev1-game/game-rpc:80
    Endpoints:
      - game-rpc:80
    NonBlock: true

  SystemRpc:
    #Target: k8s://dev1-game/system-rpc:80
    Endpoints:
      - system-rpc:80
    NonBlock: true

  TransRpc:
    #Target: k8s://dev1-game/transaction-rpc:80
    Endpoints:
      - transaction-rpc:80
    NonBlock: true

  Log:
    ServiceName: user-api
    Level: error
    Mode: console
    KeepDays: 3

  Timezone: America/Sao_Paulo