config:
  Name: mq
  Host: 0.0.0.0
  Port: 80

  AdminRpc:
    Endpoints:
      - admin-rpc:80
    NonBlock: true
    Timeout: 999999999
    Middlewares:
      Duration: false

  UserRpc:
    Endpoints:
      - user-rpc:80
    NonBlock: true
    Timeout: 999999999
    Middlewares:
      Duration: false

  MqConfig:
    Username: admin
    Password: admin123456
    Host: 192.168.124.69
    Port: 5674
    VHost: my_vhost
    Exchange: game_logic
    QueuesConf:
      - Name: PayRechargeCallback
        AutoAck: true
        Describe: "充值回调,逻辑是调用user-rpc去更新订单状态钱包状态vip等级信息，然后发送mq消息recharge_finish"
        BindRouteKey: "#.pay_recharge_callback.#"
        Consumer: PayRechargeCallback
      - Name: PayWithdrawCallback
        AutoAck: true
        Describe: "提现回调,逻辑是调用user-rpc去更新订单状态钱包状态"
        BindRouteKey: "#.pay_withdrawal_callback.#"
        Consumer: PayWithdrawCallback
      - Name: RechargeSelfReward
        AutoAck: true
        Describe: "充值奖励,逻辑是调用user-rpc去更新钱包信息"
        BindRouteKey: "#.recharge_selfReward.#"
        Consumer: RechargeSelfReward
      - Name: RechargePromotionCommissionReward
        AutoAck: true
        Describe: "充值推广佣金奖励,逻辑是调用user-rpc去更新钱包信息,佣金记录信息"
        BindRouteKey: "#.recharge_promotionCommissionReward.#"
        Consumer: RechargePromotionCommissionReward
      - Name: RechargeActivityReward
        AutoAck: true
        Describe: "充值活动奖励,逻辑是调用user-rpc去更新钱包信息,活动奖励信息"
        BindRouteKey: "#.recharge_activityReward.#"
        Consumer: RechargeActivityReward
      - Name: VipUpgradeReward
        AutoAck: true
        Describe: "vip升级奖励,逻辑是调用user-rpc去更新钱包信息"
        BindRouteKey: "#.vip_upgrade.#"
        Consumer: VipUpgrade
      - Name: BetGameCashBack
        AutoAck: true
        Describe: "游戏现金返水,逻辑是调用user-rpc去更新钱包信息,游戏返水信息"
        BindRouteKey: "#.bet_gameCashBack.#"
        Consumer: BetGameCashBack
      - Name: BetPromotionCommissionReward
        AutoAck: true
        Describe: "投注推广佣金奖励,逻辑是调用user-rpc去更新钱包信息,佣金记录信息"
        BindRouteKey: "#.bet_promotionCommissionReward.#"
        Consumer: BetPromotionCommissionReward
      - Name: BetActivityReward
        AutoAck: true
        Describe: "投注活动奖励,逻辑是调用user-rpc去更新钱包信息,活动奖励信息"
        BindRouteKey: "#.bet_activityReward.#"
        Consumer: BetActivityReward
      - Name: RegisterSelfReward
        AutoAck: true
        Describe: "注册奖励,逻辑是调用user-rpc去更新钱包信息"
        BindRouteKey: "#.register_selfReward.#"
        Consumer: RegisterSelfReward
      - Name: SignInSelfReward
        AutoAck: true
        Describe: "签到奖励,逻辑是调用user-rpc去更新钱包信息"
        BindRouteKey: "#.signIn_selfReward.#"
        Consumer: SignInSelfReward
      - Name: DownLoadSelfReward
        AutoAck: true
        Describe: "下载奖励,逻辑是调用user-rpc去更新钱包信息"
        BindRouteKey: "#.downLoad_selfReward.#"
        Consumer: DownLoadSelfReward
    SenderConf:
      - Event: pay_recharge_callback #发送方是pay-rpc
        RouteKey: pay_recharge_callback
      - Event: pay_withdrawal_callback #发送方是pay-rpc
        RouteKey: pay_withdrawal_callback
      - Event: recharge_finish # 发送方是user-rpc
        RouteKey: recharge_selfReward.recharge_promotionCommissionReward.recharge_activityReward.vip_upgrade
      - Event: bet_finish #发送方是user-rpc
        RouteKey: bet_gameCashBack.bet_promotionCommissionReward.bet_activityReward.vip_upgrade
      - Event: register_finish # 发送方是user-rpc
        RouteKey: register_selfReward
      - Event: signIn_finish #发送方是user-rpc
        RouteKey: signIn_selfReward
      - Event: downLoad_finish #发送方是user-rpc
        RouteKey: downLoad_selfReward