config:
  Name: mq
  ListenOn: 0.0.0.0:80
  Mode: dev

  SantQueue:
    ClusterID: test-cluster
    ClientID: mq-1
    Hosts: nats://nats-stream-node:4222

  Redis:
    Host: redis-master:6379
    Pass: game123456
    Type: node
  UserRpc:
    #Target: k8s://dev1-game/user-rpc:80
    Endpoints:
      - user-rpc:80
    NonBlock: true

  GameRpc:
    #Target: k8s://dev1-game/game-rpc:80
    Endpoints:
      - game-rpc:80
    NonBlock: true

  SystemRpc:
    #Target: k8s://dev1-game/system-rpc:80
    Endpoints:
      - system-rpc:80
    NonBlock: true