config:
  Name: recharge
  Host: 0.0.0.0
  Port: 80
  Timeout: 10000
  Mode: dev

  JwtAuth:
    AccessSecret: ae0536f9-6450-4606-8e13-5a19ed505da0
    AccessExpire: 2592000

  SystemRpc:
    Target: k8s://dev1-game/system-rpc:80
    NonBlock: true

  UserRpc:
    Target: k8s://dev1-game/user-rpc:80
    NonBlock: true

  TransactionRpc:
    Target: k8s://dev1-game/transaction-rpc:80
    NonBlock: true