config:
  Name: admin.api
  Host: 0.0.0.0
  Port: 80
  Timeout: 99999
  MaxBytes: 10485760
  Mode: dev

  ObjectName: test
  ServerOpenDate: "2023-06-13 00:00:00"
  Timezone: America/Sao_Paulo

  Mysql:
    DataSource: root:123456@tcp(mysql:3306)/newfoguetebet?charset=utf8mb4&parseTime=true


  Cache:
    - Host: redis-master:6379

  Redis:
    Host: redis-master:6379
    Pass: game123456
    Type: node

  SantQueue:
    ClusterID: test-cluster
    ClientID: test-1
    Hosts: nats://nats-stream-node:4222

  Log:
    ServiceName: user-rpc
    Level: debug
    Mode: console
    KeepDays: 3

  Aws:
    AppId: xxxxxxxxxxxxxxxx
    Secret: xxxxxxxxxxxxxxx
    Region: sa-east-1
    OpenSearch:
      Remote: false
      Domain: http://es-node:9200

  JwtAuth:
    AccessSecret: ae0536f9-6450-4606-8e13-5a19ed505da0
    AccessExpire: 2592000
    BufferTime: 7200

  BuryPointRpc:
    Target: k8s://dev1-game/burypoint-rpc:80
    NonBlock: true

  TransactionRpc:
    Target: k8s://dev1-game/transaction-rpc:80
    NonBlock: true

  UserRpc:
    Target: k8s://dev1-game/user-rpc:80
    NonBlock: true

  SystemRpc:
    Target: k8s://dev1-game/system-rpc:80
    NonBlock: true
