config:
  Name: admin.api
  Host: 0.0.0.0
  Port: 80

  Mode: dev
  Middlewares:
    Log: false
  ObjectName: test
  AccountId: 6eb54c27ea0a6d8a2550ab9fb45d4da8
  AccessKeyId: 8a34ed2b1cf885574d861f6044a01ddf
  AccessKeySecret: 0a142b03fdef53222251408ecb86b8eda80835fa8582e99bd0ee9b6f00dc2a77
  ServerOpenDate: "2023-06-13 00:00:00"
  Timezone: America/Sao_Paulo

  Mysql:
    DataSource: root:123456@tcp(basic-tidb.tidb-cluster.svc.cluster.local:4000)/new_game?charset=utf8mb4&parseTime=true

  Redis:
    Host: redis-master:6379
    Pass: game123456
    Type: node

  JwtAuth:
    AccessSecret: ae0536f9-6450-4606-8e13-5a19ed505da0
    AccessExpire: 2592000
    BufferTime: 7200
    MultiSite: false
  Telemetry:
    Name: admin-api
    Endpoint: http://jaeger-collector.kube-public.svc.cluster.local:14268/api/traces
    Sampler: 1.0
    Batcher: jaeger

  DevServer:
    Port: 90
    MetricsPath: /metrics
    EnableMetrics: true
  AdminRpc:
    Endpoints:
      - admin-rpc:80
    NonBlock: true
    Timeout: 999999999
    Middlewares:
      Duration: false
  PayRpc:
    Endpoints:
      - pay-rpc:80
    NonBlock: true
    Timeout: 999999999
    Middlewares:
      Duration: false
  UserRpc:
    Endpoints:
      - user-rpc:80
    NonBlock: true
    Timeout: 999999999
    Middlewares:
      Duration: false