apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin.fullname" . }}
  labels:
    {{- include "admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 90
      targetPort: 90
      protocol: TCP
      name: metrics-port
  selector:
    {{- include "admin.selectorLabels" . | nindent 4 }}
