config:
  Name: burypoint.api
  Host: 0.0.0.0
  Port: 80
  Mode: dev
  BuryPointRpc:
    #Target: k8s://dev1-game/burypoint-rpc:80
    Endpoints:
      - burypoint-rpc:80
    NonBlock: true

  Redis:
    Host: redis-master:6379
    Pass: game123456
    Type: node

  JwtAuth:
    AccessSecret: ae0536f9-6450-4606-8e13-5a19ed505da0
    AccessExpire: 2592000