config:
  Name: transaction.rpc
  ListenOn: 0.0.0.0:80
  Timeout: 10000

  Mode: dev


  Mysql:
    DataSource: root:123456@tcp(mysql:3306)/newfoguetebet?charset=utf8mb4&parseTime=true

  Cache:
    - Host: redis-master:6379

  Redis:
    Host: redis-master:6379
    Pass: game123456
    Type: node

  Aws:
    AppId: xxxxxx
    Secret: xxxxxxxx
    Region: sa-east-1
    OpenSearch:
      Remote: false
      Domain: http://es-node:9200

  BuryPointRpc:
    #Target: k8s://dev1-game/burypoint-rpc:80
    Endpoints:
      - burypoint-rpc:80
    NonBlock: true

  SystemRpc:
    #Target: k8s://dev1-game/system-rpc:80
    Endpoints:
      - system-rpc:80
    NonBlock: true

  UserRpc:
    #Target: k8s://dev1-game/user-rpc:80
    Endpoints:
      - user-rpc:80
    NonBlock: true

  SantQueue:
    ClusterID: test-cluster
    ClientID: trans-1
    Hosts: nats://nats-stream-node:4222