config:
  Name: game.rpc
  Mode: dev
  ListenOn: 192.168.124.10:8081
  Etcd:
    Hosts:
      - 192.168.124.10:2379
    Key: game.rpc

  Mysql:
    DataSource: root:123456@tcp(192.168.124.100:3306)/newfoguetebet?charset=utf8mb4&parseTime=true

  Cache:
    - Host: 192.168.124.10:6379

  Redis:
    Host: 192.168.124.10:6379
    Type: node

  Aws:
    AppId: xxxxxxx
    Secret: xxxxxxxx
    Region: sa-east-1
    OpenSearch:
      Remote: false
      Domain: http://192.168.124.10:9200