config:
  Name: game.rpc
  Mode: dev
  ListenOn: 0.0.0.0:80

  Mysql:
    DataSource: root:123456@tcp(mysql:3306)/newfoguetebet?charset=utf8mb4&parseTime=true

  Cache:
    - Host: redis-master:6379

  Redis:
    Host: redis-master:6379
    Pass: game123456
    Type: node

  Aws:
    AppId: xxxxxxx
    Secret: xxxxxxxx
    Region: sa-east-1
    OpenSearch:
      Remote: false
      Domain: http://es-node:9200