apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: {{ include "admin-rpc.fullname" . }}
spec:
  endpoints:
    - interval: 15s
      port: metrics-port
  selector:
    matchLabels:
      app.kubernetes.io/name: admin-rpc
