config:
  Name: system.rpc
  ListenOn: 0.0.0.0:80
  Mode: dev

  Mysql:
    DataSource: root:123456@tcp(mysql:3306)/newfoguetebet?charset=utf8mb4&parseTime=true

  Cache:
    - Host: redis-master:6379
      Pass: game123456

  Redis:
    Host: redis-master:6379
    Pass: game123456
    Type: node