config:
  Name: user.rpc
  ListenOn: 0.0.0.0:80
  Prod: false
  Timeout: 99999

  Mode: dev


  JwtAuth:
    AccessSecret: ae0536f9-6450-4606-8e13-5a19ed505da0
    AccessExpire: 2592000

  Snowflake:
    WorkerID: 1
    DatacenterID: 1

  Mysql:
    DataSource: root:123456@tcp(mysql:3306)/newfoguetebet?charset=utf8mb4&parseTime=true

  Redis:
    Host: redis-master:6379
    Pass: game123456
    Type: node

  Cache:
    - Host: redis-master:6379

  Aws:
    AppId: xxxxxxxx
    Secret: xxxxxxxx
    Region: sa-east-1
    OpenSearch:
      Remote: false
      Domain: http://es-node:9200
  Email:
    From: no-reply@foguetebet.com
    Host: smtpout.secureserver.net
    Port: 465
    Password: MFGLr6UPvjpyDgGK

  TPAuth:
    Google:
      ClientID: aaaa
      ClientSecret: bbbbb
      RedirectURL: ccccc

  BuryPointRpc:
    #Target: k8s://dev1-game/burypoint-rpc:80
    Endpoints:
      - burypoint-rpc:80
    NonBlock: true

  SystemRpc:
    #Target: k8s://dev1-game/system-rpc:80
    Endpoints:
      - system-rpc:80
    NonBlock: true

  Log:
    ServiceName: user-rpc
    Level: debug
    Mode: console
    KeepDays: 3

  SantQueue:
    ClusterID: test-cluster
    ClientID: game-api-1
    Hosts: nats://nats-stream-node:4222