apiVersion: v1
kind: Service
metadata:
  name: nats-stream-node
  labels:
    {{- include "nats-stream.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30422
  selector:
    {{- include "nats-stream.selectorLabels" . | nindent 4 }}
